[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.20.8"
  NPM_VERSION = "10.9.3"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = false

# Force specific Node.js version
[context.production.environment]
  NODE_VERSION = "18.20.8" 